"""Linking a dbt project: read it, keep its manifest fresh, summarize it for the agent.

The dbt project stays where it is. Boards are written to a separate scratch project
(the workspace), whose generated ``dbt_charts.yml`` points back at the dbt project with
``dbt_project_dir:``. ``ref()`` and ``source()`` in board SQL then resolve against the
dbt project's ``target/manifest.json``, which ``dbt parse`` builds from the project files.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

CONFIG_MARKER = "# generated by dct-chat"
SOURCE_NAME = "warehouse"
PROMPT_BUDGET = 14_000  # characters of model/column detail handed to the agent
PARSE_TIMEOUT = 180
MAX_DISCOVERY = 10  # models whose columns are read from the warehouse when the YAML has none


_ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")


def _plain(text: str) -> str:
    """Terminal output without its color codes, for showing in the page."""
    return _ANSI.sub("", text)


class ProjectError(Exception):
    """The dbt project can't be used; the message says why, in plain words."""


@dataclass(frozen=True)
class DbtProject:
    path: Path
    name: str
    profile: str
    target: str | None
    profiles_dir: Path | None
    watched: tuple[str, ...]  # dirs (relative to path) whose files feed the manifest
    target_path: str

    @property
    def manifest(self) -> Path:
        return self.path / self.target_path / "manifest.json"


@dataclass
class Summary:
    adapter: str = ""
    models: int = 0
    sources: int = 0
    metrics: int = 0
    generated_at: str = ""
    prompt_text: str = ""
    marts: list[str] = field(default_factory=list)
    undocumented: list[str] = field(default_factory=list)  # shown models whose YAML lists no columns


def load_project(path: str | Path, target: str | None = None, profiles_dir: str | Path | None = None) -> DbtProject:
    root = Path(path).expanduser().resolve()
    config = root / "dbt_project.yml"
    if not config.is_file():
        raise ProjectError(f"{root} has no dbt_project.yml, so it isn't a dbt project.")
    try:
        data = yaml.safe_load(config.read_text()) or {}
    except yaml.YAMLError as exc:
        raise ProjectError(f"dbt_project.yml could not be read: {exc}") from exc
    if not data.get("name") or not data.get("profile"):
        raise ProjectError("dbt_project.yml needs both `name` and `profile`.")
    watched = tuple(
        d
        for key in ("model-paths", "macro-paths", "seed-paths", "snapshot-paths")
        for d in (data.get(key) or ([] if key != "model-paths" else ["models"]))
    )
    return DbtProject(
        path=root,
        name=str(data["name"]),
        profile=str(data["profile"]),
        target=target,
        profiles_dir=Path(profiles_dir).expanduser().resolve() if profiles_dir else None,
        watched=watched,
        target_path=str(data.get("target-path") or "target"),
    )


def write_charts_config(workspace: Path, project: DbtProject) -> str | None:
    """Write the scratch project's dbt_charts.yml. Returns a warning if one already exists
    that this app didn't generate (it's left alone)."""
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "charts").mkdir(exist_ok=True)
    config = workspace / "dbt_charts.yml"
    if config.exists() and CONFIG_MARKER not in config.read_text():
        return f"{config} wasn't generated by dct-chat, so it was left as is."
    source: dict[str, object] = {"type": "dbt_profile", "profile": project.profile}
    if project.target:
        source["target"] = project.target
    if project.profiles_dir:
        source["profiles_dir"] = str(project.profiles_dir)
    body = yaml.safe_dump(
        {"dbt_project_dir": str(project.path), "sources": {SOURCE_NAME: source}}, sort_keys=False
    )
    config.write_text(f"{CONFIG_MARKER}\n{body}")
    return None


def manifest_is_stale(project: DbtProject) -> bool:
    """True if the manifest is missing or any model/macro/seed file is newer than it."""
    if not project.manifest.is_file():
        return True
    built = project.manifest.stat().st_mtime
    candidates = [project.path / "dbt_project.yml"]
    for rel in project.watched:
        for dirpath, _dirs, files in os.walk(project.path / rel):
            candidates += [Path(dirpath) / f for f in files if f.endswith((".sql", ".yml", ".yaml", ".csv", ".py"))]
    return any(p.stat().st_mtime > built for p in candidates if p.exists())


async def parse(project: DbtProject) -> str | None:
    """Run `dbt parse` so the manifest matches the project. Returns an error message, or None."""
    dbt = shutil.which("dbt", path=str(Path(sys.executable).parent)) or shutil.which("dbt")
    if dbt is None:
        return "dbt isn't installed in this environment."
    args = [dbt, "parse", "--project-dir", str(project.path)]
    if project.profiles_dir:
        args += ["--profiles-dir", str(project.profiles_dir)]
    elif (project.path / "profiles.yml").is_file():
        args += ["--profiles-dir", str(project.path)]
    if project.target:
        args += ["--target", project.target]
    proc = await asyncio.create_subprocess_exec(
        *args, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT, cwd=project.path
    )
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), PARSE_TIMEOUT)
    except asyncio.TimeoutError:
        proc.kill()
        return f"dbt parse took longer than {PARSE_TIMEOUT}s."
    if proc.returncode != 0:
        tail = "\n".join(_plain(out.decode(errors="replace")).strip().splitlines()[-8:])
        return f"dbt parse failed:\n{tail}"
    return None


def _is_mart(node: dict[str, object]) -> bool:
    parts = Path(str(node.get("original_file_path", ""))).parts
    name = str(node.get("name", ""))
    return "marts" in parts or name.startswith(("fct_", "dim_", "mart_"))


def _clip(text: str, n: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= n else text[: n - 1] + "…"


def summarize(project: DbtProject, discovered: dict[str, list[str]] | None = None) -> Summary:
    """Digest the manifest into what the agent needs: models, columns, sources, metrics.

    `discovered` supplies columns read from the warehouse for models whose YAML documents none.
    """
    discovered = discovered or {}
    try:
        manifest = json.loads(project.manifest.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ProjectError(f"The manifest couldn't be read: {exc}") from exc
    nodes = manifest.get("nodes", {})
    models = [
        n
        for n in nodes.values()
        if n.get("resource_type") == "model"
        and n.get("package_name") == project.name
        and (n.get("config") or {}).get("enabled", True)
        and (n.get("config") or {}).get("materialized") != "ephemeral"
    ]
    models.sort(key=lambda n: (not _is_mart(n), n["name"]))  # marts first
    sources = [s for s in manifest.get("sources", {}).values() if s.get("package_name") == project.name]
    metrics = [m for m in manifest.get("metrics", {}).values() if m.get("package_name") == project.name]

    lines: list[str] = []
    undocumented: list[str] = []
    used = 0
    shown = 0
    for node in models:
        cols = node.get("columns") or {}
        col_text = ", ".join(
            f"{c['name']}" + (f" ({c['data_type']})" if c.get("data_type") else "") + (f": {_clip(c['description'], 60)}" if c.get("description") else "")
            for c in cols.values()
        )
        line = (
            f"- `{node['name']}`"
            f" [{(node.get('config') or {}).get('materialized', 'model')}{', mart' if _is_mart(node) else ''}]"
            + (f" {_clip(node['description'], 140)}" if node.get("description") else "")
            + (
                f"\n    columns: {col_text}"
                if col_text
                else f"\n    columns (read from the warehouse): {', '.join(discovered[node['name']])}"
                if node["name"] in discovered
                else "\n    columns: not documented; check with a query"
            )
        )
        if used + len(line) > PROMPT_BUDGET:
            break
        lines.append(line)
        used += len(line)
        shown += 1
        if not col_text and len(undocumented) < MAX_DISCOVERY:
            undocumented.append(node["name"])
    sections = [f"dbt models in `{project.name}` ({shown} of {len(models)} shown, marts first):\n" + "\n".join(lines)]
    if shown < len(models):
        sections.append(f"{len(models) - shown} more models exist; find them with `dct query {SOURCE_NAME} ...` or ask the user.")
    if sources:
        sections.append(
            "dbt sources (use `{{ source('<source>', '<table>') }}`):\n"
            + "\n".join(f"- {s['source_name']}.{s['name']}" + (f": {_clip(s['description'], 100)}" if s.get("description") else "") for s in sources[:40])
        )
    if metrics:
        sections.append(
            "Business metrics defined in the project (use these definitions when the user names them):\n"
            + "\n".join(f"- {m['name']}" + (f" ({m['label']})" if m.get("label") else "") + (f": {_clip(m['description'], 140)}" if m.get("description") else "") for m in metrics[:40])
        )
    return Summary(
        adapter=str((manifest.get("metadata") or {}).get("adapter_type", "")),
        models=len(models),
        sources=len(sources),
        metrics=len(metrics),
        generated_at=str((manifest.get("metadata") or {}).get("generated_at", "")),
        prompt_text="\n\n".join(sections),
        marts=[n["name"] for n in models if _is_mart(n)][:6],
        undocumented=undocumented,
    )


def check_connection(workspace: Path, source: str, timeout: int = 90) -> tuple[bool, str]:
    """Run a trivial query through dct against the source; (ok, human-readable detail)."""
    dct = Path(sys.executable).parent / "dct"
    try:
        out = subprocess.run(
            [str(dct), "query", source, "SELECT 1 AS ok"],
            capture_output=True,
            text=True,
            cwd=workspace,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return False, f"No answer from the warehouse within {timeout}s."
    text = _plain(out.stdout + out.stderr).strip()
    if out.returncode == 0:
        return True, "Connected: a test query ran successfully."
    return False, "\n".join(text.splitlines()[-6:]) or "The test query failed."


def _type_hint(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    text = str(value)
    if len(text) >= 10 and text[4] == "-" and text[7] == "-" and text[:4].isdigit():
        return "date" if len(text) == 10 else "timestamp"
    return "text"


async def discover_columns(workspace: Path, names: list[str], timeout: int = 60) -> dict[str, list[str]]:
    """Read column names (with a rough type from a sample row) for models the YAML doesn't describe.

    Best effort: any model that can't be queried is simply left out.
    """
    dct = Path(sys.executable).parent / "dct"
    gate = asyncio.Semaphore(4)

    async def one(name: str) -> tuple[str, list[str]] | None:
        sql = f"SELECT * FROM {{{{ ref('{name}') }}}} LIMIT 1"
        async with gate:
            proc = await asyncio.create_subprocess_exec(
                str(dct), "query", SOURCE_NAME, sql, "--json",
                cwd=workspace, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL,
            )
            try:
                out, _ = await asyncio.wait_for(proc.communicate(), timeout)
            except asyncio.TimeoutError:
                proc.kill()
                return None
        try:
            result = json.loads(out)
        except json.JSONDecodeError:
            return None
        if not result.get("success") or not result.get("columns"):
            return None
        sample = (result.get("data") or [{}])[0]
        return name, [f"{c} ({h})" if (h := _type_hint(sample.get(c))) else c for c in result["columns"]]

    found = await asyncio.gather(*(one(n) for n in names))
    return dict(r for r in found if r)
